# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from imagenes import imagenes

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 545)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, -10, 381, 361))
        self.label.setStyleSheet("image: url(:/inicio/Captura de Pantalla 2023-10-19 a las 10.02.20.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(-10, -20, 481, 621))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 400, 91, 31))
        self.pushButton.setStyleSheet("background-color: rgb(173, 175, 225);\n"
"font: 11pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 480, 91, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(173, 175, 225);\n"
"font: 11pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 360, 241, 31))
        self.label_3.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(39, 7, 69);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 450, 371, 21))
        self.label_4.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(39, 7, 69);")
        self.label_4.setObjectName("label_4")
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Inicia Sesión"))
        self.pushButton_2.setText(_translate("Dialog", "Regístrate"))
        self.label_3.setText(_translate("Dialog", "¿Tienes ya una cuenta?"))
        self.label_4.setText(_translate("Dialog", "¿Todavía no has empezado esta aventura?"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
